### PR TITLE
Adds field for discord-id 

### PR DESCRIPTION
**Pull request by Wreck-X**
#11 
adds migrations that updates the members table adds `discord_id` field  members table for improving amD functionalities for status update  tracking

### CODE REVIEW

**Comment by Wreck-X** [comment]
@he1senbrg can you look into #11 there's a few more stuff to be added

**Comment by he1senbrg** [comment]
will do

**Comment by Wreck-X** [comment]
@he1senbrg any updates on this?

**Comment by he1senbrg** [comment]
@hkx05 Is working on this

**Comment by Wreck-X** [comment]
how is this going along @hkx05?

**Comment by harikrishnatp** [comment]
yeah, almost done.

**Review by he1senbrg — APPROVED** [review]

**Pull request merged**
